// Copyright IBM Corp. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: common/crypto.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionMechanism int32

const (
	EncryptionMechanism_ECIES EncryptionMechanism = 0
	EncryptionMechanism_DBE   EncryptionMechanism = 1
)

// Enum value maps for EncryptionMechanism.
var (
	EncryptionMechanism_name = map[int32]string{
		0: "ECIES",
		1: "DBE",
	}
	EncryptionMechanism_value = map[string]int32{
		"ECIES": 0,
		"DBE":   1,
	}
)

func (x EncryptionMechanism) Enum() *EncryptionMechanism {
	p := new(EncryptionMechanism)
	*p = x
	return p
}

func (x EncryptionMechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionMechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_common_crypto_proto_enumTypes[0].Descriptor()
}

func (EncryptionMechanism) Type() protoreflect.EnumType {
	return &file_common_crypto_proto_enumTypes[0]
}

func (x EncryptionMechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionMechanism.Descriptor instead.
func (EncryptionMechanism) EnumDescriptor() ([]byte, []int) {
	return file_common_crypto_proto_rawDescGZIP(), []int{0}
}

type DBEKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Srs     []byte `protobuf:"bytes,1,opt,name=srs,proto3" json:"srs,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DBEKey) Reset() {
	*x = DBEKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_crypto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBEKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEKey) ProtoMessage() {}

func (x *DBEKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_crypto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEKey.ProtoReflect.Descriptor instead.
func (*DBEKey) Descriptor() ([]byte, []int) {
	return file_common_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *DBEKey) GetSrs() []byte {
	if x != nil {
		return x.Srs
	}
	return nil
}

func (x *DBEKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EncryptionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mechanism EncryptionMechanism `protobuf:"varint,1,opt,name=mechanism,proto3,enum=common.crypto.EncryptionMechanism" json:"mechanism,omitempty"`
	// Either:
	//
	//	(1) a serialized X.509 certificate, if 'encryptionMechanism' == 'ECIES', or
	//	(2) a base64 encoding of an SRS structure as 'DBEKey', if 'encryptionMechanism' == 'DBE'
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *EncryptionInfo) Reset() {
	*x = EncryptionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_crypto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionInfo) ProtoMessage() {}

func (x *EncryptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_crypto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionInfo.ProtoReflect.Descriptor instead.
func (*EncryptionInfo) Descriptor() ([]byte, []int) {
	return file_common_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptionInfo) GetMechanism() EncryptionMechanism {
	if x != nil {
		return x.Mechanism
	}
	return EncryptionMechanism_ECIES
}

func (x *EncryptionInfo) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_common_crypto_proto protoreflect.FileDescriptor

var file_common_crypto_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x06, 0x44, 0x42, 0x45, 0x4b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x72, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x64, 0x0a, 0x0e, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x09,
	0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x63, 0x68, 0x61, 0x6e,
	0x69, 0x73, 0x6d, 0x52, 0x09, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x2a, 0x29, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x63, 0x68, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x43, 0x49, 0x45, 0x53,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x42, 0x45, 0x10, 0x01, 0x42, 0x73, 0x0a, 0x31, 0x6f,
	0x72, 0x67, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x63,
	0x61, 0x63, 0x74, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70,
	0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x63, 0x61, 0x63, 0x74, 0x69, 0x2f, 0x77,
	0x65, 0x61, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_crypto_proto_rawDescOnce sync.Once
	file_common_crypto_proto_rawDescData = file_common_crypto_proto_rawDesc
)

func file_common_crypto_proto_rawDescGZIP() []byte {
	file_common_crypto_proto_rawDescOnce.Do(func() {
		file_common_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_crypto_proto_rawDescData)
	})
	return file_common_crypto_proto_rawDescData
}

var file_common_crypto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_crypto_proto_goTypes = []interface{}{
	(EncryptionMechanism)(0), // 0: common.crypto.EncryptionMechanism
	(*DBEKey)(nil),           // 1: common.crypto.DBEKey
	(*EncryptionInfo)(nil),   // 2: common.crypto.EncryptionInfo
}
var file_common_crypto_proto_depIdxs = []int32{
	0, // 0: common.crypto.EncryptionInfo.mechanism:type_name -> common.crypto.EncryptionMechanism
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_crypto_proto_init() }
func file_common_crypto_proto_init() {
	if File_common_crypto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_crypto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBEKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_crypto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_crypto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_crypto_proto_goTypes,
		DependencyIndexes: file_common_crypto_proto_depIdxs,
		EnumInfos:         file_common_crypto_proto_enumTypes,
		MessageInfos:      file_common_crypto_proto_msgTypes,
	}.Build()
	File_common_crypto_proto = out.File
	file_common_crypto_proto_rawDesc = nil
	file_common_crypto_proto_goTypes = nil
	file_common_crypto_proto_depIdxs = nil
}
